# Doctr requires python >=3.5
language: python
python:
  - 3.6

# This gives Doctr the key we've generated
sudo: false
env:
  global:
    # Doctr deploy key for ocean-eddy-cpt/ocean-eddy-cpt.github.io
    - secure: "i5ccSJCip0As1DBmHz/bFRhus4qQG0zHKx59qPljmHhrJFx3OdCRnmGZP7cgKQUPivqpUzBUv/ebBHIQCG0m4xQ6bG9bgy+2x+nK5fujRDBulp00mR6fpDV/m56fUVHJOzdLFynCxJv8E09MbvgCMR8kiiOP6ny19vduAx2AhaTiTVkEa0O796uj/J69P2Q3lG/UYJ6eZ/O+MZzBJpRuOcQoaqUCT1kL02j/zNtrU9kxa3LxismAILin7L78CbXO1IjLU9691SwKRdIyisYqY//RPujoqXxsCGSxVNR3ueOzWYhmEhzSHUYwlqEi+t+JiVsrgz8BrupneWPBT8ARG6E1c/hnfpRdSxRRipvndsrNi7f0Y4tWV3eenB3gOFPPOBkn+cvMq+zhMpQdtvnpWA+dZtGPOmDvffuAMKxcjpLKHO1iYhauUyurFGI4Dag3uz95Woap0Kd+SqA3Zk2bIIpRqyCFGaA+U/wurtM29YXGOl8PhiffJX5lLVEb6Da7k3lJh4Df+h1AKZXb31GIMfVZB6WzSXkAmKA5RC05vttxNIVoBpInYsElRuVYgJBRRdqoPaLXE34kLoUU7660MdAB+jbY3C9Re/Q4TfCw+zbVoLMoTLi81Fvm0Y9I2Ni0UA7tOPwGZBi+P+FtVKGVuxAxMLYLaB6dKMnow+H1Ad8="

install:
  - pip install -r requirements.txt

# This is the script to build the docs on travis, then deploy
script:
  - set -e
  - cd doc
  - make html
  - cd ..
  - doctr deploy . --built-docs doc/_build/html
